### ISSUE TITLE
NFC material blocks are called "X Block" instead of "Block of X"

### ISSUE THREAD

**Issue by Roadhog360** [LO6AN/New-Frontier-Craft#46]

**Comment by Roadhog360** [comment]
Fixing in v3.5 so translations can stay the same between versions.

**Comment by VivianTheFox** [comment]
Is this really a "bug" per-se? It seems stranger that to refer to a stone block, you'd need to refer to it as a "Block of Stone", as opposed to a block of stone. Which is.. a block of stone. But not the Block of Stone, which is a different thing.

I feel like the change would introduce more issues than it'd resolve. Plus, "Block of" adds more length to the already kinda ridiculously long string length of the names. Especially as following that naming convention, you'd need to fix Nether Block's to be called "Block of Nether Stone". Because "Block of Nether" sounds... strange. I mean we _could_ do that... but I don't think it'd be the best call. But if we did go ahead and rename it to Nether Stone, then a cross-cut Nether Stone block would be "Block of Cross-Cut Nether Stone". Which is... way too long of a name for a block in my honest opinion.

**Comment by Roadhog360** [comment]
I am talking specifically about ore storage blocks. Default blocks use the latter convention and NFC uses the former. Block of Iron vs. Platinum Block, Block of Diamond vs. Copper Block etc

Also not saying that makes it okay, I just find this funny. Modern has ridiculous names like "Cracked Polished Blackstone Bricks" or "Polished Blackstone Pressure Plate" or "Waxed Weathered Cut Copper Stairs"

**Comment by VivianTheFox** [comment]
I agree with that. Ore Storage Blocks should match the Vanilla convention. I would just heavily urge the Stone Blocks to be left in place with their current naming convention, for the reasons I outlined above.

**Comment by Roadhog360** [comment]
Yeah. I was never referring to anything but ore material blocks to begin with, so anything else outside of that remains unchanged.
