### ISSUE TITLE
Worldgen Misaligned between Singleplayer and Multiplayer

### ISSUE THREAD

**Issue by VivianTheFox** [LO6AN/New-Frontier-Craft#87]
Seeds between server and client are mostly aligned, but some things like ore placement and world decorators are slightly off

**Comment by Roadhog360** [comment]
I know why this is, the decorators and ore placement code has a lot of little differences that would offset the RNG. I'm actually gonna label this as won't fix as server owners currently cannot hide the world seed because biomes are hardcoded to it. So people can't just hop on single player, find osmium or diamonds and then go there in multiplayer.

TL;DR very large-scale fix for a pretty nuanced and possibly useful bug.

I'm also gonna call this one a server-only bug.
